name: GGJ-2024 Build

on:
  schedule:
    - cron: '*/1 * * * *'  # Run every 1 minutes
    #- cron: '0 * * * *'  # Run every hour

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Notify Discord
        if: always()
        uses: fjogeleit/http-request-action@main
        with:
          method: POST
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          data: '{"content": "GitHub Actions workflow completed successfully for Unreal Engine 5.3.2!"}'
