name: Package Unreal Project

on:
  schedule:
    - cron: '0 * * * *' # Run every hour

jobs:
  package:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Unreal Engine
        uses: GameCI/UnrealEngine-GitHub-Action@v4
        with:
          engine: '5.3.2' # Use the desired Unreal Engine version

      - name: Build and Package
        run: |
          Setup.bat
          GenerateProjectFiles.bat

          # Build and package the project
          Engine/Binaries/DotNET/UnrealBuildTool.exe GGJ-2024 Win64 Development -Package -Stage -Archive -archivedirectory=Artifacts -NoVerifyCookedPlatforms -Map=ThirdPersonMap

      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: packaged-artifacts
          path: Artifacts
